CREATE DATABASE record;
USE record;
CREATE TABLE patients(  recordno int auto_increment primary key, pname varchar(100), fname varchar(100), age int , gender varchar(20), contact long, address text(500), disease varchar(100), doctor varchar(100), previousRecordNo int, dateofVisit date  );
CREATE TABLE doctor(sno int,dname varchar(100),category varchar(100),aday varchar(100),atime varchar(100));
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (1,'Rohan kappor','General Practitioner','All week','allday');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (2,'Nisha Sharma','General Practitioner','All week','allday');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (3,'Aarav Patel','General Practitioner','All week','allday');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (4,'Ananya Gupta ','General Practitioner','All week','allday');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (5,'Aditya Singh','General Practitioner','All week','allday');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (6,'Riya Mehta','Pediatrician','Monday,Wednesday,Friday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (7,'Arjun Reddy','Pediatrician','Monday,Wednesday,Friday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime)VALUES (8,'Khushi Verma','Pediatrician','Monday,Wednesday,Friday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (9,'Vikram Chatterjee','Pediatrician','Monday,Wednesday,Friday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (10,'Sneha Desai','Pediatrician','Monday,Thursday,Sunday','5pm-8pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (11,'Aryan Malhotra','Pediatrician','Monday,Thursday,Sunday','5pm-8pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (12,'Swara Lyer','Pediatrician','Tuesday,Thursday,Saturday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (13,'Rajat Dubey','Pediatrician','Tuesday,Thursday,Saturday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (14,'Ishita Joshi','Pediatrician','Tuesday,Thursday,Saturday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (15,'Rahul Bhatia','Pediatrician','Tuesday,Thursday,Saturday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (16,'Kavya kumar','Obstettrician and Gynecologists','Monday,Wednesday,Friday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (17,'Kartika Shah','Obstettrician and Gynecologists','Monday,Wednesday,Friday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (18,'Anika Sharma','Obstettrician and Gynecologists','Monday,Wednesday,Friday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (19,'Pooja Choudhary','Obstettrician and Gynecologists','Monday,Wednesday,Friday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (20,'Nisha Patel','Obstettrician and Gynecologists','Monday,Thursday,Sunday','5pm-8pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (21,'Ananya Pandey','Obstettrician and Gynecologists','Monday,Thursday,Sunday','5pm-8pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (22,'Radhika kumar','Obstettrician and Gynecologists','Tueday,Thursday,Saturday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (23,'Harshita Shah','Obstettrician and Gynecologists','Tueday,Thursday,Saturday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (24,'Kiara Sharma','Obstettrician and Gynecologists','Tueday,Thursday,Saturday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (25,'Aditi Meena','Obstettrician and Gynecologists','Tuesday,Thursday,Saturday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (26,'Dhruv Trivedi','Psychiatrist','Monday,Wednesday,Friday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (27,'Alok Sinha','Psychiatrist','Monday,Wednesday,Friday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (28,'Natasha Srinivasan','Psychiatrist','Monday,Wednesday,Friday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (29,'Sahil Rana','Psychiatrist','Monday,Wednesday,Friday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (30,'Muskan Khan','Psychiatrist','Monday,Thursday,Sunday','5pm-8pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (31,'Yash Patel','Psychiatrist','Monday,Thursday,Sunday','5pm-8pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (32,'Riya Thakur','Psychiatrist','Tuesday,Thursday,Saturday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (33,'Dev Khanna','Psychiatrist','Tuesday,Thursday,Saturday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (34,'Aanya Mehta','Psychiatrist','Tuesday,Thursday,Saturday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (35,'Arnav Suri','Psychiatrist','Tuesday,Thursday,Saturday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (36,'Aditi Kapoor','Oncologist','Monday,Wednesday,Friday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (37,'Karan kumar','Oncologist','Monday,Wednesday,Friday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (38,'Ansukha Menon','Oncologist','Monday,Wednesday,Friday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (39,'Abhishek Sharma','Oncologist','Monday,Wednesday,Friday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (40,'Tanvi Iyer','Oncologist','Monday,Thursday,Sunday','5pm-8pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (41,'Rohit Chaudhary','Oncologist','Monday,Thursday,Sunday','5pm-8pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (42,'Anjali Sood','Oncologist','Tuesday,Thursday,Saturday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (43,'Varun Gupta','Oncologist','Tuesday,Thursday,Saturday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (44,'Shruti Rajan','Oncologist','Tuesday,Thursday,Saturday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (45,'Akash Verma','Oncologist','Tuesday,Thursday,Saturday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (46,'Divya Reddy','Nephrologist','Monday,Wednesday,Friday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (47,'Vivek Deshmukh','Nephrologist','Monday,Wednesday,Friday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (48,'Esha Saxena','Nephrologist','Monday,Wednesday,Friday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (49,'Sameer Khan','Nephrologist','Monday,Wednesday,Friday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (50,'Priya Patel','Nephrologist','Monday,Thursday,Sunday','5pm-8pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (51,'Rohini Malhotra','Nephrologist','Monday,Thursday,Sunday','5pm-8pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (52,'Harsh Shah','Nephrologist','Tuesday,Thursday,Saturday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (53,'Riya Verma','Nephrologist','Tuesday,Thursday,Saturday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (54,'Rajeev Kapoor','Nephrologist','Tuesday,Thursday,Saturday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (55,'Kirti Joshi','Nephrologist','Tuesday,Thursday,Saturday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (56,'Ankit Rao','Endocrinologist','Monday,Wednesday,Friday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (57,'Nandini Kumar','Endocrinologist','Monday,Wednesday,Friday','9pm-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (58,'Pranav Mehta','Endocrinologist','Monday,Wednesday,Friday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (59,'Preeti Singh','Endocrinologist','Monday,Wednesday,Friday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (60,'Sujay Sharma','Endocrinologist','Monday,Thursday,Sunday','5pm-8pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (61,'Sanjana Sen','Endocrinologist','Monday,Thursday,Sunday','5pm-8pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (62,'Rishi Gupta','Endocrinologist','Tuesday,Thursday,Saturday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (63,'Ishita Chatterjee','Endocrinologist','Tuesday,Thursday,Saturday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (64,'Jay Patel','Endocrinologist','Tuesday,Thursday,Saturday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (65,'Neha Desai','Endocrinologist','Tuesday,Thursday,Saturday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (66,'Surya Menon','Gastroenterologist','Monday,Wednesday,Friday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (67,'Shreya Gupta','Gastroenterologist','Monday,Wednesday,Friday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (68,'Armaan Chopra','Gastroenterologist','Monday,Wednesday,Friday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (69,'Tanisha Singh','Gastroenterologist','Monday,Wednesday,Friday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (70,'Raj Kapoor','Gastroenterologist','Monday,Thursday,Sunday','5pm-8pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (71,'Natasha Shah','Gastroenterologist','Monday,Thursday,Sunday','5pm-8pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (72,'Vivan Mehra','Gastroenterologist','Tuesday,Thursday,Saturday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (73,'Aaradhya Prajapati','Gastroenterologist','Tuesday,Thursday,Saturday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (74,'Sanket Patel','Gastroenterologist','Tuesday,Thursday,Saturday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (75,'Akshara Chawla','Gastroenterologist','Tuesday,Thursday,Saturday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (76,'Virat Sharma','Dermatologist','Monday,Wednesday,Friday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (77,'Ananya Verma','Dermatologist','Monday,Wednesday,Friday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (78,'Aniket Kumar','Dermatologist','Monday,Wednesday,Friday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (79,'Maya Sharma','Dermatologist','Monday,Wednesday,Friday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (80,'Raghav Sharma','Dermatologist','Monday,Wednesday,Friday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (81,'Sanya Mehta','Dermatologist','Monday,Thursday,Sunday','5pm-8pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (82,'Varun Singh','Dermatologist','Tuesday,Thursday,Saturday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (83,'Ayan Khan','Dermatologist','Tuesday,Thursday,Saturday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (84,'Siya Sharma','Dermatologist','Tuesday,Thursday,Saturday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (85,'Armaan Khan','Dermatologist','Tuesday,Thursday,Saturday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (86,'Riya Prajapati','Dentist','Monday,Wednesday,Friday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (87,'Pranav Singh','Dentist','Monday,Wednesday,Friday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (88,'Sneha Rathore','Dentist','Monday,Wednesday,Friday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (89,'Akhil Kapoor','Dentist','Monday,Wednesday,Friday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (90,'Aisha Joshi','Dentist','Monday,Thursday,Sunday','5pm-8pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (91,'Arjun Kapoor','Dentist','Monday,Thursday,Sunday','5pm-8pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (92,'Divya Sharma','Dentist','Tuesday,Thursday,Saturday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (93,'Vedant Deshmukh','Dentist','Tuesday,Thursday,Saturday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (94,'Nisha Srinivasan','Dentist','Tuesday,Thursday,Saturday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (95,'Kunal Sharma','Dentist','Tuesday,Thursday,Saturday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (96,'Siddharth Malhotra','Ophthalmologist','Monday,Wednesday,Friday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (97,'Anshka Gupta','Ophthalmologist','Monday,Wednesday,Friday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (98,'Ravi Verma','Ophthalmologist','Monday,Wednesday,Friday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (99,'Riya Rajput','Ophthalmologist','Monday,Wednesday,Friday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (100,'Alok Mishra','Ophthalmologist','Monday,Thursday,Sunday','5pm-8pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (101,'Jaya Sinha','Ophthalmologist','Monday,Thursday,Sunday','5pm-8pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (102,'Abhay Rana','Ophthalmologist','Tuesday,Thursday,Saturday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (103,'Kavya Chawla','Ophthalmologist','Tuesday,Thursday,Saturday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (104,'Sameer Seth','Ophthalmologist','Tuesday,Thursday,Saturday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (105,'Swati Kapoor','Ophthalmologist','Tuesday,Thursday,Saturday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (106,'Vivek Mehrota','Otolaryngologist','Monday,Wednesday,Friday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (107,'Sneha Chawda','Otolaryngologist','Monday,Wednesday,Friday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (108,'Karthik Patel','Otolaryngologist','Monday,Wednesday,Friday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (109,'Sannvi Trivedi','Otolaryngologist','Monday,Wednesday,Friday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (110,'Naman Kumar','Otolaryngologist','Monday,Thursday,Sunday','5pm-8pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (111,'Maya Sen','Otolaryngologist','Monday,Thursday,Sunday','5pm-8pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (112,'Arjun Prajapati','Otolaryngologist','Tuesday,Thursday,Saturday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (113,'Avni Trivedi','Otolaryngologist','Tuesday,Thursday,Saturday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (114,'Vedant Singh','Otolaryngologist','Tuesday,Thursday,Saturday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (115,'Anjali Thakur','Otolaryngologist','Monday,Wednesday,Friday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (116,'Ayush Jain','Orthopedic','Monday,Wednesday,Friday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (117,'Abhinav Dubey','Orthopedic','Monday,Wednesday,Friday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (118,'Mahima Patil','Orthopedic','Monday,Wednesday,Friday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (119,'Radhika Sharma','Orthopedic','Monday,Wednesday,Friday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (120,'Rohit Rajput','Orthopedic','Monday,Thursday,Sunday','5pm-8pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (121,'Akshat Jain','Orthopedic','Monday,Thursday,Sunday','5pm-8pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (122,'Surbhi Jain','Orthopedic','Tuesday,Thursday,Saturday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (123,'Shobhit Prajapati','Orthopedic','Tuesday,Thursday,Saturday','9am-1pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (124,'Sarthak Mehta','Orthopedic','Tuesday,Thursday,Saturday','1pm-5pm');
INSERT INTO doctor (sno,dname,category,aday,atime) VALUES (125,'Khushi Yadav','Orthopedic','Tuesday,Thursday,Saturday','1pm-5pm');
INSERT INTO doctor(sno,dname,category,aday,atime) Values(126,'Siya Singh','Neurosurgeon','Monday,Wednesday,Friday','9am-1pm');
INSERT INTO doctor(sno,dname,category,aday,atime) Values(127,'Virat Rao','Neurosurgeon','Monday,Wednesday,Friday','9am-1pm');
INSERT INTO doctor(sno,dname,category,aday,atime) Values(128,'Rohan Patil','Neurosurgeon','Monday,Wednesday,Friday','1pm-5pm');
INSERT INTO doctor(sno,dname,category,aday,atime) Values(129,'Tanisha Mehta','Neurosurgeon','Monday,Wednesday,Friday','1pm-5pm');
INSERT INTO doctor(sno,dname,category,aday,atime) Values(130,'Preeti Gupta','Neurosurgeon','Monday,Thursday,Sunday','5pm-8pm');
INSERT INTO doctor(sno,dname,category,aday,atime) Values(131,'Muskan Soni','Neurosurgeon','Monday,Thursday,Sunday','5pm-8pm');
INSERT INTO doctor(sno,dname,category,aday,atime) Values(132,'Tara Sharma','Neurosurgeon','Tuesday,Thursday,Saturday','9am-1pm');
INSERT INTO doctor(sno,dname,category,aday,atime) Values(133,'Natasha Chawda','Neurosurgeon','Tuesday,Thursday,Saturday','9am-1pm');
INSERT INTO doctor(sno,dname,category,aday,atime) Values(134,'Dinesh Jaiswal','Neurosurgeon','Tuesday,Thursday,Saturday','1pm-5pm');
INSERT INTO doctor(sno,dname,category,aday,atime) Values(135,'Alvira Khan','Neurosurgeon','Tuesday,Thursday,Saturday','1pm-5pm');
INSERT INTO doctor(sno,dname,category,aday,atime)VALUES(136,'Sneha Chawda','Cardiothoracic','Monday,Wednesday,Friday','9am-1pm');
INSERT INTO doctor(sno,dname,category,aday,atime)VALUES(137,'Disha Chawda','Cardiothoracic','Monday,Wednesday,Friday','9am-1pm');
INSERT INTO doctor(sno,dname,category,aday,atime)VALUES(138,'Krishna Ojha','Cardiothoracic','Monday,Wednesday,Friday','1pm-5pm');
INSERT INTO doctor(sno,dname,category,aday,atime)VALUES(139,'Ayush Singh','Cardiothoracic','Monday,Wednesday,Friday','1pm-5pm');
INSERT INTO doctor(sno,dname,category,aday,atime)VALUES(140,'Harsh Nagar','Cardiothoracic','Monday,Thursday,Sunday','5pm-8pm');
INSERT INTO doctor(sno,dname,category,aday,atime)VALUES(141,'Vedik Sen','Cardiothoracic','Monday,Thursday,Sunday','5pm-8pm');
INSERT INTO doctor(sno,dname,category,aday,atime)VALUES(142,'Harshita Yadav','Cardiothoracic','Tuesday,Thursday,Saturday','9am-1pm');
INSERT INTO doctor(sno,dname,category,aday,atime)VALUES(143,'Radhika Sharma','Cardiothoracic','Tuesday,Thursday,Saturday','9am-1pm');
INSERT INTO doctor(sno,dname,category,aday,atime)VALUES(144,'Harsh Prajapati','Cardiothoracic','Tuesday,Thursday,Saturday','1pm-5pm');
INSERT INTO doctor(sno,dname,category,aday,atime)VALUES(145,'Noshin Khan','Cardiothoracic','Tuesday,Thursday,Saturday','1pm-5pm');

